---
- name: Copy Main Icinga2 Configuration
  template: src=icinga2.conf.j2
            dest={{ icinga2_main_conf }}
            backup=yes
            owner=root
            group=root
            mode=0644
  when: "{{ icinga2_conf_global | default('') | length}}"
  notify:
   - restart icinga2

- name: Copy Check Commands Configuration
  template: src=icinga2_check_commands.j2
            dest={{ icinga2_conf_d }}/check_commands.conf
            backup=yes
            owner=root
            group=root
            mode=0644
  when: "{{ check_commands | default('') | length}}"
  notify:
   - restart icinga2

- name: Set a TicketSalt if configured
  lineinfile:
    dest: /etc/icinga2/constants.conf
    regexp: ^const TicketSalt
    line: const TicketSalt = "{{ icinga2_ticket_salt | default('') }}"

- name: Remove monitoring config files (for using the API to add hosts etc)
  file:
    name: "/etc/icinga2/conf.d/{{ item }}"
    state: absent
  with_items:
    - hosts.conf
    - services.conf
  when: icinga2_remove_monitoring_config
